# Generated by Django 2.1.5 on 2019-01-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190122_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.ImageField(blank=True, default='featured/default.png', upload_to='featured'),
        ),
    ]
