# Generated by Django 2.1.5 on 2019-01-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190122_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='featured/default.png', upload_to='featured'),
        ),
    ]
