# Generated by Django 2.1.5 on 2019-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190122_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='featured/default.jpeg', upload_to='featured'),
        ),
    ]
