# Generated by Django 2.1.5 on 2019-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190122_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='featured/default.jpg', upload_to=''),
        ),
    ]
